language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
 - pip install -e .[dev]

script:
 - py.test cloudpickle_generators
 - flake8 cloudpickle_generators

notifications:
  email: false
